project:
  title: "Dissipation Learning in Active Matter"
  type: website

website:
  back-to-top-navigation: true
  page-footer:
    center: "Made with Quarto (cp branch)"
  sidebar:
    search: true
    style: "docked"
    contents:
      - section: "Personal"
        icon: person-fill
        contents:
          - activity_log/landing.qmd
      - section: "Shared"
        icon: diagram-3-fill
      - text: "Zotero library"
        icon: bookmarks-fill
        href: "https://www.zotero.org/groups/5210328/dissipation_learning_in_active_matter/library"
    tools:
      - icon: git
        menu:
          - text: "GitHub mirror"
            href: "https://github.com/ldrtch/msci-wiki"

format:
  html:
    toc: true
    toc-depth: 2
    toc-title: Contents
    code-fold: false
    page-layout: article
    html-math-method: mathjax
    anchor-sections: true
    smooth-scroll: true
    theme: cyborg
    mainfont: sans-serif
    linkcolor: rgb(220,0,0)
jupyter: python3
