---
title: "Home"
---

## Information

Welcome to the home page (or landing spot) for the Dissipative Learning in Active Matter project! This page links to a few useful pages for the project as a whole. For weekly lab notes, see the [activity log](./activity_log/landing.qmd), also available on the sidebar.

Some generally useful links for day to day sharing and work:

- [Deadlines](./shared/deadlines.qmd) : A quick list of deadlines for this project.
- [Repository information](./shared/repo.qmd) : Info on how to set up the repository.
- [Commands Information](./shared/gitinfo.qmd) : Useful commands for navigating the repository and publishing pages.

Most important links can be found on the sidebar. However, of particular note are the following:

- [Github Notes Repository](https://github.com/LDRTCH/msci-wiki) : Contains all of the notes and scripts referenced throughout this page.
- [Persistent Exclusion Process Github Repository](https://github.com/dlactivematter/persistent-exclusion-process) : Contains all the relevant code for this project. Note that some of the scripts in this notebook reference slightly different functions due to differences between my and my lab partner's functions. For the few exact functions that I used in this project and which misalign, consult my uploaded file.
