# Motivational Report

# 0. Table of Contents

0. Table of Contents
1. Introduction
2. Original Motivational Report
3. Supervisor Feedback 
4. Responding to Supervisor Feedback

# 1. Introduction

This is the landing spot for work on the Motivational Report. It was initially prompted in Week 2 as a way to get familiarised with the literature; it is expected to be a considerable part of the Interim Report, whose [deadline](./../shared/deadlines.qmd) is in Week 9.

# 2. Original Motivational Report ([Week 2](./../activity_log/week2.qmd))

###### Pasted from "Motivational Report" chapter in Week 2

Active matter is, broadly, a subcategory of matter systems distingushed primarily by energy input homogenously distributed across all constituents (agents) of the system, which in turn set their own self-propelled motion across a force-free medium (for instance, the forces between particles and the fluid they move through cancel)[1]. The agents therefore have direct access to energy, and use it to autonomously propel and direct themselves (with different models and situations allowing for various degrees of freedom). The study of active matter is generally grounded in (but not limited to) observed behaviour of biological agents, as they are the primary (though not only) examples of active matter in nature.

The evident motivation in studying active matter is that it helps understand biological behaviours, and therefore the natural world. Macroscopically, the construction of theoretical models can help explain, and to a limited degree predict, the behaviour of animals (such as locusts) undergoing collectively-emergent swarming behaviours (where each animal can be treated as its own autonomous agent, sharing the same generally stable ‘rules’ of altering speed and orientation while interacting with each other and the environment)[2]. This is not limited to what can be termed ‘simple’ behaviour; human behaviour can be partially mapped and understood within physically-indexed accounts of autonomous choices within (overtly or suggestively) constrained collective action. Interesting examples are swarming behaviours identified in traffic, crowd disasters and concerts[3] (note however that physical models are sometimes challenged in literature due to potential oversimplifications, insofar as, for instance, cognitive heuristics under duress might deal holistically, rather than individually, with other human agents[4]). Microscopically, active matter models offer insight into understanding how hierarchically-organised emergence happens within cell tissues, and how it may be leveraged by medicine[5].

Outside of biology, active matter research serves to emulate, or otherwise learn from, naturally-occurring behaviours in order to analyse a potentially more general thermodynamic state. Due to the necessarily dissipative use of energy within self-organised agents, and their internally-induced behaviour, active matter is not described by the statistical mechanics of equilibrium states. The question then arises whether, through quantitative computation and qualitative modelling/theorising, the thermodynamic laws of equilibria can be modified and generalised to non-equilibrium states, and how these generalisations hold as departure from equilibrium through various means is increased[6]. These generalisations would, ideally, collapse into the known statistical thermodynamics states within the equilibrium limit. These insights, in turn, would facilitate the creation of synthetic active matter, whose potential, although speculatory, ranges from the biomedical application of nanomachine targeted drug delivery possibilities to the location-mapping application of nanoscopic/microscopic enivronmental sensing[7].

The feature in active matter of converting stored and homogenously available energy, such as chemical potential, into mechanical work is also of great importance to the field: understanding how this can work and how to facilitate, among other things, long-term energy access across the active matter substance is a key pursuit of nanotechnology[8]. Statistical and computational models can lend insight into individual and collective dynamics, and in turn give way to new experimental designs of nano/micromechanical systems.


499 words.

#### References

1. Active matter: quantifying the departure from equilibrium. Flenner & Szamel

2. From Disorder to Order in Marching Locusts. Buhl et al. (2006)

3. Collective Motion of Humans in Mosh and Circle Pits at Heavy Metal Concerts. Silverberg et al. (2013)

4. How simple rules determine pedestrian behavior and crowd disasters. Moussaid, Helbing & Theraulaz (2011)

5. Active matter at the interface between materials science and cell biology. Needleman & Zvonimir (2017)

6. Phase Separation and Multibody Effects in Three-Dimensional Active Brownian Particles. Turci & Wilding (2021)

7. Nano/Micromotors in Active Matte. Lv, Yank & Li (2022)

8. Catalytic Nanomotors: Autonomous Movement of Striped Nanorods, Paxton et al. (2004)

# 3. Supervisor Feedback ([Week 3](./../activity_log/week3.qmd))

###### Comments prefaced with FT and hyperlinked, commented initially on week2.md in main repository (pure markdown version of [Week2](./../activity_log/week2.qmd))

Active matter is, broadly, a subcategory of matter systems [FT "matter systems is unclear]() distingushed primarily by energy input homogenously distributed across all constituents (agents) of the system, which in turn set their own self-propelled motion across a force-free medium (for instance, the forces between particles and the fluid they move through cancel [FT not exactly. Theres i no mechanical equilibrium. On the contrary, there is dissipation]() )[1]. The agents therefore have *direct* access to energy, and use it to autonomously propel and direct themselves (with different models and situations allowing for various degrees of freedom). The study of active matter is generally grounded in (but not limited to) observed behaviour of biological agents, as they are the primary (though not only) examples of active matter in nature. [FT very good]()

The evident motivation in studying active matter is that it helps understand biological behaviours, and therefore the natural world [FT be more precise: it is the world of living organisms, which constantly dissipate energy to perform their biological functions](). Macroscopically, the construction of theoretical models can help explain, and to a limited degree predict, the behaviour of animals (such as locusts) undergoing collectively-emergent swarming behaviours (where each animal can be treated as its own autonomous agent, sharing the same generally stable 'rules' of altering speed and orientation while interacting with each other and the environment)[2]. This is not limited to what can be termed 'simple' behaviour; human behaviour can be partially mapped and understood within physically-indexed accounts of autonomous choices within (overtly or suggestively) constrained collective action. [FT: You are onto something here. Physicist Andrea Cavagna likes to say that *"Physics gauges the surprise in biology"*  ]()Interesting examples are swarming behaviours identified in traffic, crowd disasters and concerts[3] (note however that physical models are sometimes challenged in literature due to potential oversimplifications, insofar as, for instance, cognitive heuristics under duress might deal holistically, rather than individually, with other human agents[4]  [FT not clear to me, please explain]() ).  Microscopically, active matter models offer insight into understanding how hierarchically-organised emergence happens within cell tissues, and how it may be leveraged by the medical sciences[5].

Outside of biology, active matter research serves to emulate, or otherwise learn from naturally-occurring behaviours in order to analyse a potentially more general thermodynamic state [FT "state" is not a good word. Are you thinking about a more general thermodynamic framework?]() . Due to the necessarily dissipative use of energy within self-organised agents, and their internally-induced behaviour, active matter is not described by the statistical mechanics of equilibrium states. The question then arises whether, through quantitative computation and qualitative modelling/theorising, the thermodynamic laws of equilibrium can be modified and generalised to non-equilibrium states, and how these generalisations hold as departure from equilibrium through various means is increased[6] [FT: not easy to read, but the idea is important: we can be just slight off equilibrium, and have a so-called linear-response regime, or we could be beyond linear response]() . These generalisations would, ideally, collapse into the known statistical thermodynamics states within the equilibrium limit. These insights, in turn, would facilitate the creation of synthetic active matter, whose potential, although speculatory, ranges from the biomedical application of nanomachine targeted drug delivery possibilities to the location-mapping application of nanoscopic/microscopic enivronmental sensing[7]. 

The feature in active matter of converting stored and homogenously available energy, such as chemical potential, into mechanical work is also of great importance to the field: understanding how this can work and how to facilitate, among other things, long-term energy access across the active matter substance is a key pursuit of nanotechnology[8]. Statistical and computational models can lend insight into individual and collective dynamics, and in turn give way to new experimental designs of nano/micromechanical systems. 

[FT: You could get into more specifics, illustrating some examples of interesting behaviorus such as pattern formation or phase separation]()

<br>

502 words.

<br>
 
#### References

1. Active matter: quantifying the departure from equilibrium. Flenner & Szamel

2. From Disorder to Order in Marching Locusts. Buhl et al. (2006)

3. Collective Motion of Humans in Mosh and Circle Pits at Heavy Metal Concerts. Silverberg et al. (2013)

4. How simple rules determine pedestrian behavior and crowd disasters. Moussaid, Helbing & Theraulaz (2011)

5. Active matter at the interface between materials science and cell biology. Needleman & Zvonimir (2017)

6. Phase Separation and Multibody Effects in Three-Dimensional Active Brownian Particles. Turci & Wilding (2021)

7. Nano/Micromotors in Active Matte. Lv, Yank & Li (2022)

8. Catalytic Nanomotors: Autonomous Movement of Striped Nanorods, Paxton et al. (2004)

# 4. Responding to Supervisor Feedback [Week 4](./../activity_log/week4.qmd)

My original context is presented, with the supervisor comments hyperlinked and prefaced by "FT". Underneath I add my own comments in the form of bullet points. Only the commented parts of the report are shown.

Active matter is, broadly, a subcategory of matter systems [FT “matter systems is unclear]() distingushed primarily by energy input homogenously distributed across all constituents (agents) of the system, which in turn set their own self-propelled motion across a force-free medium (for instance, the forces between particles and the fluid they move through cancel [FT not exactly. Theres i no mechanical equilibrium. On the contrary, there is dissipation]()

- Here I was looking for a broad category to place active matter into; matter systems is indeed too vague. I would have been better off calling it a subcategory of soft matter systems.

- I don't know exactly where I got the mechanical equilibrium confusion. I may have read some very specific thing that I generalised, but yes, dissipation ought to happen - one of the most important aspects of active matter is the requirement of supplying each autonomous agent with a steady energy supply which they steadily (or perhaps not so steadily in more complex models) use up.

The evident motivation in studying active matter is that it helps understand biological behaviours, and therefore the natural world [FT be more precise: it is the world of living organisms, which constantly dissipate energy to perform their biological functions](). Macroscopically, the construction of theoretical models can help explain, and to a limited degree predict, the behaviour of animals (such as locusts) undergoing collectively-emergent swarming behaviours (where each animal can be treated as its own autonomous agent, sharing the same generally stable 'rules' of altering speed and orientation while interacting with each other and the environment)[2]. This is not limited to what can be termed 'simple' behaviour; human behaviour can be partially mapped and understood within physically-indexed accounts of autonomous choices within (overtly or suggestively) constrained collective action. [FT: You are onto something here. Physicist Andrea Cavagna likes to say that *"Physics gauges the surprise in biology"*  ]()Interesting examples are swarming behaviours identified in traffic, crowd disasters and concerts[3] (note however that physical models are sometimes challenged in literature due to potential oversimplifications, insofar as, for instance, cognitive heuristics under duress might deal holistically, rather than individually, with other human agents[4]  [FT not clear to me, please explain]() ).  Microscopically, active matter models offer insight into understanding how hierarchically-organised emergence happens within cell tissues, and how it may be leveraged by the medical sciences[5].

- I forgot that 'natural world' in English tends to refer more to general physical processes rather than specifically living organisms; I'll try to be more specific regarding what active matter models help with understanding.

- From the brief look I managed to take at the literature, it seems that discussion of human behaviour in terms of physical systems is quite contentious. In hindsight, I should spend more than a sentence explaining this: the 'cognitive heuristics' argument for holism refers to the way humans deal with other humans in immediate crises. Many models will have an individual agent deal with other (in some way) adjacent agents individually; that is to say, it defines its relationship to each agent in turn, and then computes its behaviour. There are psychological arguments that this is not the case, and that instead humans might under duress conceptualise crowds (still) as a collective, and take actions in relation to the collective itself. At the time of writing this, it is unclear to me whether there are any active matter models that apply this 'holistic' method; the writers I cited, I believe, were criticising the models that do not attempt to do so. This is the case with the basic models I have engaged with so far (such as ABPs). It's hard to imagine (though not impossible) how such a model can be implemented, but I don't doubt that newer human-tracking physical models might work in this direction.

- Either way, I'll look into Andrea Cavagna's work. I'm interested in exploring this point more in detail.

Outside of biology, active matter research serves to emulate, or otherwise learn from naturally-occurring behaviours in order to analyse a potentially more general thermodynamic state [FT "state" is not a good word. Are you thinking about a more general thermodynamic framework?]() . Due to the necessarily dissipative use of energy within self-organised agents, and their internally-induced behaviour, active matter is not described by the statistical mechanics of equilibrium states. The question then arises whether, through quantitative computation and qualitative modelling/theorising, the thermodynamic laws of equilibrium can be modified and generalised to non-equilibrium states, and how these generalisations hold as departure from equilibrium through various means is increased[6] [FT: not easy to read, but the idea is important: we can be just slight off equilibrium, and have a so-called linear-response regime, or we could be beyond linear response]() . These generalisations would, ideally, collapse into the known statistical thermodynamics states within the equilibrium limit. These insights, in turn, would facilitate the creation of synthetic active matter, whose potential, although speculatory, ranges from the biomedical application of nanomachine targeted drug delivery possibilities to the location-mapping application of nanoscopic/microscopic enivronmental sensing[7]. 

- I take the point that 'state' is the wrong word; another loss in translation. I did mean a more general thermodynamic framework; thermodynamic 'state' implies thermal equilibrium, which is exactly what active matter does not have!

- I do get a bit long-winded here; I'll try to rephrase this paragraph a bit and make sentences more readable

[FT: You could get into more specifics, illustrating some examples of interesting behaviorus such as pattern formation or phase separation]()

- Yes, I'll look into examples of pattern formation, as those tend to be quite demonstrative of what active matter study can do. 

#5. Fleshing out Motivational Report [Weeks 5-6](./../activity_log/week5-6.qmd)

Active matter is, broadly, a subcategory of condensed matter systems distingushed primarily by energy input homogenously distributed across all constituents (agents) of the system, which in turn set their own self-propelled motion across a medium. The agents therefore have *direct* access to energy, and use it to autonomously propel and direct themselves (with different models and situations allowing for various degrees of freedom). The study of active matter is generally grounded in (but not limited to) observed behaviour of biological agents, as they are the primary (though not only) examples of active matter in nature.

The evident motivation in studying active matter is that it helps understand biological behaviours, and therefore the world of living organisms, where energy is constantly dissipated in order to perform various biological functions. Macroscopically, the construction of theoretical models can help explain, and to a limited degree predict, the behaviour of animals (such as locusts) undergoing collectively-emergent swarming behaviours (where each animal can be treated as its own autonomous agent, sharing the same generally stable ‘rules’ of altering speed and orientation while interacting with each other and the environment)[2]. 

This biological emulation through physical models is not limited to what can be termed ‘simple’ behaviour; human behaviour can be partially mapped and understood within physically-indexed accounts of autonomous choices within (overtly or suggestively) constrained collective action. Interesting examples are swarming behaviours identified in traffic, crowd disasters and concerts[3]. Note however that physical models are sometimes challenged in literature due to potential oversimplifications, insofar as, for instance, cognitive heuristics (the autonomous individual behaviour of a human) under duress might deal holistically, rather than individually, with other human agents[4]. The issue is that most active matter systems only form individual relationships between agents, and do not account for the way an agent interacts with the group as a whole - the resulting individual behaviour is merely a summation of the agent's response to each other agent around it. There are psychological arguments that this is not the case, and that instead humans might under duress conceptualise crowds as a collective, and take actions in relation to the collective itself. This objection rests on the assumption that this holistic heuristic does not *emerge* from individual relations, of course (in which case mapping relationships strictly between individuals is unproblematic).

These insights lead to the exploration of various models. For flocks of birds, individual cogntive heuristics tend to suffice - self-propelled particles with adaptive movement patterns based on neighbours can accurately reproduce some migrational patterns [5]. Microscopically, active matter models offer insight into understanding how hierarchically-organised emergence happens within cell tissues, and how it may be leveraged by medicine[6]. Bacteria lends a great example for exploring the intertwining of phenomena to be emulated by active matter. Some strains (such as *Bacillus subtilis*) can be modelled using both direct physical interaction (between individuals) and long-distance biochemical signalling (within the collective), with complexity and clustering developing in response to harsh external conditions [7]. The latter interaction is called quorum sensing, the adaptation of the individual to local population density; this has developed into its own active matter branch of individual-to-collective behaviour [8]. Using such models, it is possible to recover the aforementioned human holistic cognitive heuristics [9].

Outside of biology, active matter research serves to emulate, or otherwise learn from, naturally-occurring behaviours in order to analyse a potentially more general thermodynamic framework. Due to the necessarily dissipative use of energy within self-organised agents, and their internally-induced behaviour, active matter is not described by the statistical mechanics of equilibrium states. The question then arises whether, through quantitative computation and qualitative modelling/theorising, the thermodynamic laws of equilibria can be modified and generalised to non-equilibrium states. Exploring how these generalisations would hold as departure from equilibrium through various means is increased is then paramount[10]. These generalisations would, ideally, collapse into the known statistical thermodynamics states within the equilibrium limit. These insights, in turn, would facilitate the creation of synthetic active matter, whose potential, although speculatory, ranges from the biomedical application of nanomachine targeted drug delivery possibilities to the location-mapping application of nanoscopic/microscopic enivronmental sensing[11].

The feature in active matter of converting stored and homogenously available energy, such as chemical potential, into mechanical work is also of great importance to the field: understanding how this can work and how to facilitate, among other things, long-term energy access across the active matter substance is a key pursuit of nanotechnology[12]. Statistical and computational models can lend insight into individual and collective dynamics, and in turn give way to new experimental designs of nano/micromechanical systems.


756 words.

#### References

1. Active matter: quantifying the departure from equilibrium. Flenner & Szamel

2. From Disorder to Order in Marching Locusts. Buhl et al. (2006)

3. Collective Motion of Humans in Mosh and Circle Pits at Heavy Metal Concerts. Silverberg et al. (2013)

4. How simple rules determine pedestrian behavior and crowd disasters. Moussaid, Helbing & Theraulaz (2011)

5. Novel Type of Phase Transition in a System of Self-Driven Particles, Vicsek et al. (1995)

6. Active matter at the interface between materials science and cell biology. Needleman & Zvonimir (2017)

7. Formation of complex bacterial colonies via self-generated vortices, Czirok et al. (1996)

8. Self-organization of active particles by quorum sensing rules, Bäuerle et al. (2018)

9. Quorum sensing as a mechanism to harness the wisdom of the crowds, Moreno-Gámez et al. (2023)

10. Phase Separation and Multibody Effects in Three-Dimensional Active Brownian Particles. Turci & Wilding (2021)

11. Nano/Micromotors in Active Matte. Lv, Yank & Li (2022)

12. Catalytic Nanomotors: Autonomous Movement of Striped Nanorods, Paxton et al. (2004)




