<script type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_CHTML">
</script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [['$','$'], ['\\(','\\)']],
      processEscapes: true},
      jax: ["input/TeX","input/MathML","input/AsciiMath","output/CommonHTML"],
      extensions: ["tex2jax.js","mml2jax.js","asciimath2jax.js","MathMenu.js","MathZoom.js","AssistiveMML.js", "[Contrib]/a11y/accessibility-menu.js"],
      TeX: {
      extensions: ["AMSmath.js","AMSsymbols.js","noErrors.js","noUndefined.js"],
      equationNumbers: {
      autoNumber: "AMS"
      }
    }
  });
</script>


# Week 1

### 0. Table of Contents

0. Table of Contents
1. Goals
2. Communication/Recording Method
3. Information Gathering

### 1. Goals

The main goal of week 1 is to get an introductory grasp of the literature regarding active matter.

The secondary goal of week 1 is to set up a communication and recording method for sharing files and information easily throughout this project.

### 2. Communication/Recording Method

Communication is done through a github repository. Both myself and my lab partner have personal branches: cp and np respectively. I will try to stick to the convention of referencing my contributions in github commits and code comments as "cp". We also have a shared branch, where we upload collective work. Per the demands of this assignment, all progress will be documented individually, despite the collaborative nature of the project. There may therefore be repeats between the activity log and various files in the shared branch; wherever possible, the shared folder will be referenced rather than copied (such as the storing of programs and data).

There is also the individual gh-pages branch, which hosts a github website which should contain both shared and individual work. This may be the cleanest method of accessing the activity log, though presumably an exported pdf will be required for examination. Nonetheless, I link (embedded) all the relevant pages below:

- [github repository](https://github.com/LDRTCH/msci-wiki) (note that this is private, so it requires an access invite)

- [website landing page](https://ldrtch.github.io/msci-wiki/)

	- [personal activity log](https://ldrtch.github.io/msci-wiki/activity_log/landing.html)

There is also the matter of convention. We have set up weekly supervisor meetings on Thursday. As such, the way weeks are kept track of is slightly unconventional, purely for pragmatic reasons. Week 1, for instance, began on the first Thursday of the university year, and ended on the second Thursday of it. It might therefore seem strange to see major edits in the github repository for, say, the Week 2 activity log on Wednesday night in what would normally be called week 3. I will think of ways to make this easier to keep track of, but the system works for now. There will (hopefully) be an addendum to this paragraph if/when I clarify the record-keeping system.

### 3. Information Gathering

Taking information from the following articles:

I. The 2020 motile active roadmap

a. Introduction
	
b. Active Brownian particles: from collective phenomena to fundamental physics

II. Run-and-tumble dynamics in a crowded environment: Persistent exclusion process for swimmers

#### I. The 2020 motile active roadmap, Gompper et al.
	
#####a. Introduction, Gompper & Roland

Active matter is a class of nonequilibrium systems composed of a large number of autonomous agents

- persistently out of equilibrium (constituents continuously consume energy)

	- absence of equilibrium concepts

		- detailed balance

		- Gibbs ensemble & free energy

		- time-reversal symmetry

- therefore theories must be constructed on:

	- symmetries:

		- polar shape (regarding polarity of molecules)

		- nematic shape (regarding molecules that are aligned loosely parallel)

		- interactions of agents

	- conservation laws

	- dynamic rules

- examples are agent-based standard models

	- <b>active Brownian particles</b>

	- squirmers
	(complemented by continuum field theory)

- aim is creation of artificial active matter (synthetic micro/nanomachines)

	- look to biological active matter

		- propulsion mechanisms (rotation, translation and periodic altering of shape)

			- cilia

			- flagella

		- navigation strategies

			- chemotaxis: movement/orientation along chemical concentration gradient (toward or away from stimulus)

			- phototaxis: movement/orientation towards or away from light

		(what is the scale lower limit of such behaviour?)

	- as such, suggested synthetic micro/nanomachines can utilise:

		- phoresis

			- diffusiophoresis: motion of species A in response to concentration gradient in colloidal species B

			- thermophoresis: motion in mixture of particles along temperature gradient (tendency of light molecules to hot and heavy particles to cold)

- swarming: spontaneous self-organisation of active agents in large numbers -> emergent coordinated collective motion on various length scales

	- determined by

		- agent shape

		- steric interactions

		- sensing

		- fluctuations

		- environmentally-mediated interactions

		novel phenomena:

		- motility-induced phase separation

		- active turbulence

##### b. Active Brownian particles: from collective phenomena to fundamental physics, Speck

Active matter makes use of "persistence of motion"; locally broken symmetry, rather than a global preferred direction.

Synthetic active matter employs particle shape, ultrasound, etc. to facilitate movement.

**Janus particles** as important experimental strategy of locomotion: two hemispheres with different surface properties. Example: **colloidal particles**

- solvent containing H2O2

- coat one hemisphere in catalyst for H2O2

- resulting local concentration leads to individual particle propulsion along symmetry axis
	
	- axis undergoes rotational diffusion due to fluctuation
	
		- single-particle trajectories with a *persistence length* analogous to polymers(?)
		
**Active Brownian Particles (ABPs)**

- persistent motion

- particle interactions

	- short range
	
	- typically repulsive
	
- particles aggregate into clusters (even without cohesive forces)

	- dynamic feedback between speed and density: motility-induced phase separation (MIPS)
	
#### II. Run-and-tumble dynamics in a crowded environment: Persistent exclusion process for swimmers, Soto & Golestanian

Bacteria biofilms constitute development into multicellular communities through aggregation; exhibit novel properties:

- differentiation
	
- delegation of function
	
Free bacteria, upon interacting with surfaces, adapt to the new conditions by adopting different motility modes

- by contrast, biofilms can **nucleate** when a number of bacteria settle down near a surface and become <b>completely localised</b>
		
	- [nucleation](https://en.wikipedia.org/wiki/Nucleation): first step in formation of a new thermodynamic phase or structure via self-assembly/self-organisation within a substance or mixture
		
	
		
		

	


