# Week 2

### Table of Contents

###### 0. Table of Contents
###### 1. Introduction
###### 2. Bibliography (Text List)
###### 3. Text Information
###### 4. Motivation Report

### Introduction

The goal of week 2 is to further familiarise ourselves with the literature. We are to write a quick 500-word referenced report detailing motivations for studying active matter. Notes for this week will therefore be slightly sparser, primarily sifting through the goals of various papers (their detailed processes are to be examined at a later date). Some of these tidbits of information will be taken from the texts explored in week 1; as such, overlap with week 1 information is not only possible, but very likely. Repetition was preferred over disorganised and uncatalogued information, as these notes serve both as an activity log (which must document repeats occasionally) and as a catalogue of information as it is found.

Above is a table of contents. Below is a list of all the texts utilised; further down various information is examined in order of text, so as to clarify what is taken from where. Finally, the 500-word referenced essay is given at the bottom.

### 2. Bibliography (Text List)

- Active matter: quantifying the departure from equilibrium, Flenner & Szamel

- The Mechanics and Statistics of Active Matter, Ramaswamy

### 3. Text information

#### The Mechanics and Statistics of Active Matter

This is a 2010 review of (at the time) recent progress within the field. Its main role for my current purposes is to obtain references to older papers (and therefore to their motivations), while also providing a starting definition for active matter.

- active matter can be considered as a type of material

- take active matter as condensed matter in a **nonequilibrium regime**

	- each (autonomous/active) constituent takes direct energetic input
	
		- energy input is therefore homogenously distributed in system
		
		- compare to fluid motion, for instance: energy is not supplied to each individual particle, but rather is applied (e.g. kinetically) at the boundaries: this then causes particles to push others forward, but they don't all have direct access to energy
		
		- slightly related, Ramaswamy argues in one of his [lectures](https://www.youtube.com/watch?v=o2YlVQsyIpc) that this is the key distinction of active matter, phrased as **direct access to energy** (in the fluid example above, the bulk particles have **indirect** access to energy)
	
	- 

#### Active matter: quantifying the departure from equilibrium, Flenner & Szamel




### 4. Motivation Report




